#!groovy

// Generated by IBM TransformationAdvisor
// Wed May 15 19:01:56 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'plantsbywebspherev8'
    mvnCommands = '--version'
    test='false'
}